version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  api: 
    image: api
    container_name: api
    ports:
      - 8080:8080
    links:
      - mongodb
  ui:
    image: ui
    container_name: ui
    ports:
      - 8081:8080
volumes:
  data: {}
networks:
  default:
    name: mongodb_network