version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  round-robin:
    image: macacumar97/round-robin
    container_name: round-robin
    ports:
      - 8585:8585
  api: 
    image: macacumar97/api
    container_name: api
    ports:
      - 8080:8080
    links:
      - mongodb
  ui:
    image: macacumar97/ui
    container_name: ui
    ports:
      - 8081:8080
volumes:
  data: {}